### Http request for classes

### Is classes service alive
GET localhost:8080/api/v1/classes/alive

### Is courses service alive
GET localhost:8080/api/v1/courses/alive

### Is professors service alive
GET localhost:8080/api/v1/professors/alive