### Http request for classes

GET localhost:8080/api/v1/courses/all
Authorization: {{access-token}}

###
GET localhost:8080/api/v1/courses/{id}
Authorization: {{access-token}}

###
POST localhost:8080/api/v1/courses
Content-Type: application/json
Authorization: {{access-token}}

< ./request/postClass.json

###
PUT localhost:8080/api/v1/courses/{id}
Content-Type: application/json
Authorization: {{access-token}}

< ./request/postClass.json

###
DELETE localhost:8080/api/v1/courses/{id}
Authorization: {{access-token}}
